### ISSUE TITLE
unable to pull computer prestage

### ISSUE THREAD

**Issue by phochstuhl** [cybertunnel/Jamf-Pro-Powershell#2]
After specifying Type = Computer, the request still tries to hit mobile prestage

```
> Get-PreStage -Server $server -Token $token.token -Type 'Computer' -Id 19438

cmdlet Get-PreStage at command pipeline position 1

Invoke-RestMethod: /Users/REDACTED/.local/share/powershell/Modules/JamfPro/Public/PreStage/func_Get-PreStage.ps1:165
Line |
 165 |      $response = Invoke-RestMethod $URI -Headers $Headers -Method GET
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {   "httpStatus" : 404,   "errors" : [ {     "code" :
     | "INVALID_ID",     "description" : "Mobile Device Prestage with
     | id 19438 does not exist",     "id" : "19438",     "field" :
     | "id"   } ] }

```

This is a valid computer ID, Get-Computer for the same ID returns a computer inventory record.

**Comment by cybertunnel** [comment]
Are you trying to get a device or Pre-Stage? Because the ID is very high for it to be a pre-stage.

**Comment by cybertunnel** [comment]
`Get-PreStage -Server $server -Token $token.token -Type 'Computer' -Id 16 ` Gets a prestage with the proper values. It is an error in Jamf's end that throws that the mobile pre-stage doesn't exist.

Error when attempting to get a prestage with `-Type Mobile` instead of `-Type Computer` results in the same error as you describe, but with the `-Type Computer` it returns an object that is expected
```Line |
 165 |      $response = Invoke-RestMethod $URI -Headers $Headers -Method GET
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {   "httpStatus" : 404,   "errors" : [ {     "code" :
     | "INVALID_ID",     "description" : "Mobile Device Prestage with
     | id 16 does not exist",     "id" : "16",     "field" : "id"   }
     | ] }```

**Comment by cybertunnel** [comment]
So discussed this out of band, and the issue is Jamf's side throwing the same error for both computer pre-stage and mobile pre-stage. Additionally there was a misunderstanding of what the command does. This command accepts a computer Pre-Stage ID, and provides the configuration, or the Scope if provided a `-Scope` flag. From there @phochstuhl wants to filter for specific devices to see if they are assigned the proper site.
